# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@cloudflare/workers-types@4.20260305.1" = fetchurl {
    url = "https://registry.npmjs.org/@cloudflare/workers-types/-/workers-types-4.20260305.1.tgz";
    hash = "sha512-835BZaIcgjuYIUqgOWJSpwQxFSJ8g/X1OCZFLO7bmirM6TGmVgIGwiGItBgkjUXXCPrYzJEldsJkuFuK7ePuMw==";
  };
  "hono@4.12.5" = fetchurl {
    url = "https://registry.npmjs.org/hono/-/hono-4.12.5.tgz";
    hash = "sha512-3qq+FUBtlTHhtYxbxheZgY8NIFnkkC/MR8u5TTsr7YZ3wixryQ3cCwn3iZbg8p8B88iDBBAYSfZDS75t8MN7Vg==";
  };
}